version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: ecom_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html:cached
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
            - "3000:3000"
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: ecom_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel_ecom
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: ecom_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ecom_phpmyadmin
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
